var gTopicInfo = [
	['Introduction', 'topics/idh-topic20.htm'],
	['The preparation', 'topics/idh-topic30.htm'],
	['Using the simulation', 'topics/idh-topic40.htm'],
	['The heart and its receptors', 'topics/idh-topic50.htm'],
	['The circulation and its receptors', 'topics/idh-topic60.htm'],
	['The nictitating membrane and its receptors', 'topics/idh-topic70.htm'],
	['Skeletal muscle and its receptors', 'topics/idh-topic80.htm'],
	['Drugs', 'topics/idh-topic90.htm']
];

var gAlphaIndex = [
	['a', 0, 29],
	['b', 30, 41],
	['c', 42, 78],
	['d', 79, 92],
	['e', 93, 102],
	['f', 103, 108],
	['g', 109, 112],
	['h', 113, 119],
	['i', 120, 134],
	['j', 135, 135],
	['l', 136, 140],
	['m', 141, 155],
	['n', 156, 171],
	['o', 172, 178],
	['p', 179, 196],
	['q', 197, 197],
	['r', 198, 214],
	['s', 215, 244],
	['t', 245, 261],
	['u', 262, 265],
	['v', 266, 277],
	['w', 278, 283],
	['y', 284, 284]
];

var gWordList = [
	['accelerans', [3]],
	['acetylcholine', [3, 4, 6, 7]],
	['ach', [6]],
	['achr', [6]],
	['act', [3, 4, 5]],
	['acting', [4]],
	['actions', [0]],
	['activity', [3]],
	['acts', [3, 4, 6]],
	['add', [2]],
	['adenosine', [3, 4, 5, 7]],
	['administer', [1]],
	['adrenoceptors', [3, 4, 5]],
	['adult', [1]],
	['agonist', [7]],
	['allows', [0]],
	['along', [3]],
	['alpha', [4, 5]],
	['also', [3, 4]],
	['anaesthetised', [0, 1]],
	['animal', [0]],
	['antagonist', [7]],
	['application', [6]],
	['apply', [0]],
	['arterial', [1, 3]],
	['arteries', [4]],
	['artery', [1]],
	['artificially', [1]],
	['atropine', [7]],
	['attached', [1]],
	['badr', [3]],
	['baroreceptor', [3]],
	['baroreceptors', [3]],
	['beta', [3]],
	['block', [6]],
	['blocking', [7]],
	['blood', [0, 1, 4]],
	['both', [3]],
	['bottom', [2]],
	['brachial', [1]],
	['but', [1]],
	['button', [2]],
	['calcium', [7]],
	['cannula', [1]],
	['capacity', [0]],
	['carbachol', [7]],
	['cardiac', [3]],
	['cardiovascular', [0]],
	['carotid', [1]],
	['cat', [0, 1, 2, 5]],
	['cause', [3, 4, 6]],
	['causes', [1, 5]],
	['cells', [0, 4]],
	['cervical', [1, 5]],
	['channel', [6, 7]],
	['chart', [2]],
	['chloralose', [1]],
	['cholinesterase', [7]],
	['cholinoceptor', [7]],
	['cholinoceptors', [3, 6]],
	['circulating', [3, 4, 6]],
	['circulation', [2, 4]],
	['clear', [2]],
	['click', [2]],
	['cns', [3]],
	['combination', [6]],
	['compared', [0]],
	['completed', [2]],
	['compounds', [0]],
	['connected', [1]],
	['constrict', [4]],
	['contains', [5]],
	['contract', [5]],
	['contractile', [3]],
	['contraction', [1]],
	['contracture', [6]],
	['copy', [2]],
	['cursor', [2]],
	['cut', [1]],
	['depolarization', [6]],
	['depress', [3, 5]],
	['depressing', [3]],
	['derived', [1]],
	['desensitization', [6]],
	['different', [0]],
	['directly', [6]],
	['dissected', [1]],
	['does', [6]],
	['dose', [2]],
	['doses', [2]],
	['drawn', [5]],
	['drug', [0, 2, 7]],
	['drugs', [0, 1, 2, 4, 7]],
	['effects', [0]],
	['electrode', [1]],
	['electrodes', [1]],
	['end', [1]],
	['endings', [3]],
	['endothelial', [4]],
	['exit', [2]],
	['experiment', [0, 2]],
	['exposed', [1]],
	['eye', [1, 5]],
	['fast', [1, 6]],
	['file', [2]],
	['finished', [2]],
	['force', [3]],
	['free', [1]],
	['from', [1, 2]],
	['gallamine', [7]],
	['ganglia', [3, 4]],
	['ganglion', [1, 5]],
	['ganglionic', [5, 7]],
	['hard', [2]],
	['heart', [0, 1, 3]],
	['hexamethonium', [7]],
	['high', [3]],
	['histamine', [4, 7]],
	['hooked', [1]],
	['hydrolysed', [7]],
	['inactivation', [6]],
	['increase', [3]],
	['increases', [4]],
	['indirectly', [3, 5]],
	['inhibitor', [7]],
	['inject', [2]],
	['injection', [1]],
	['innervated', [1, 4, 5, 6]],
	['innervates', [1]],
	['inserted', [1]],
	['intraperitoneal', [1]],
	['introduction', [0]],
	['intubated', [1]],
	['ion', [7]],
	['isolated', [0]],
	['junction', [1, 6]],
	['left', [1]],
	['leg', [1]],
	['ligated', [1]],
	['list', [2]],
	['load', [2]],
	['machr', [3]],
	['make', [2]],
	['many', [2]],
	['measured', [1]],
	['measurements', [2]],
	['membrane', [0, 1, 5]],
	['menu', [2]],
	['mepyramine', [7]],
	['mixture', [1]],
	['morphine', [7]],
	['mouse', [2]],
	['moving', [2]],
	['multiplicity', [0]],
	['muscarinic', [3, 4, 7]],
	['muscle', [0, 1, 3, 4, 5, 6]],
	['nachr', [3]],
	['naloxone', [7]],
	['necessary', [2]],
	['neck', [1]],
	['neostigmine', [7]],
	['nerve', [1, 3, 5, 6]],
	['nerves', [3, 4]],
	['neuromuscular', [1, 6]],
	['neuronal', [3, 5]],
	['new', [0, 2]],
	['next', [0, 1, 2, 3, 4, 5, 6]],
	['nicotinic', [1, 3, 4, 5, 6, 7]],
	['nictitating', [0, 1, 5]],
	['noradrenaline', [3, 4, 5]],
	['not', [1, 6, 7]],
	['noting', [2]],
	['observe', [0]],
	['occurs', [6]],
	['one', [1]],
	['opioid', [3, 5, 7]],
	['organ', [0]],
	['out', [2]],
	['over', [1, 2, 5]],
	['parasulphophenyltheophylline', [7]],
	['pentabarbitone', [1]],
	['pharmaceutical', [0]],
	['post', [5]],
	['pre', [5]],
	['preganglionically', [1]],
	['preparation', [0, 1]],
	['preparations', [0]],
	['present', [3]],
	['presssure', [3]],
	['pressure', [0, 1, 4]],
	['presynaptic', [3]],
	['print', [2]],
	['produce', [4]],
	['produces', [6]],
	['program', [2]],
	['prolonged', [6]],
	['protective', [5]],
	['quantitative', [2]],
	['rate', [0, 1, 3]],
	['readout', [2]],
	['receptor', [6, 7]],
	['receptors', [1, 3, 4, 5, 6]],
	['recorder', [2]],
	['reduce', [3]],
	['reduction', [1, 3]],
	['reflex', [3]],
	['release', [3, 4, 5]],
	['released', [5]],
	['releases', [3, 6]],
	['required', [2]],
	['respond', [5, 6]],
	['response', [3, 6]],
	['reveal', [0]],
	['right', [1]],
	['running', [2]],
	['save', [2]],
	['sciatic', [1, 6]],
	['screen', [0, 2]],
	['screening', [0]],
	['select', [2]],
	['selecting', [2]],
	['sensitive', [4]],
	['set', [1]],
	['shown', [1, 2]],
	['signal', [1]],
	['simulation', [0, 2]],
	['since', [6]],
	['skeletal', [0, 1, 6]],
	['slow', [3, 6]],
	['smooth', [4, 5]],
	['sodium', [6]],
	['spt', [7]],
	['standard', [2]],
	['start', [2]],
	['stimulated', [3]],
	['stimulation', [1, 5, 6]],
	['stop', [2]],
	['storage', [2]],
	['studies', [0]],
	['such', [0]],
	['superior', [5]],
	['sympathetic', [1, 4]],
	['synapse', [5]],
	['synaptic', [3, 5]],
	['systems', [0]],
	['tension', [1]],
	['terminals', [5]],
	['their', [0]],
	['this', [0, 1]],
	['tibialis', [1, 6]],
	['tissues', [0]],
	['tool', [0]],
	['trace', [2]],
	['traces', [0, 2]],
	['tracheally', [1]],
	['transducer', [1]],
	['transmissi', [3]],
	['transmitter', [3, 5]],
	['tubocurarine', [7]],
	['twitch', [1, 6]],
	['twitches', [0]],
	['type', [1]],
	['uopr', [5]],
	['upon', [4, 6]],
	['used', [0, 1]],
	['using', [2]],
	['vagus', [1, 3]],
	['value', [2]],
	['variety', [0]],
	['vasoconstriction', [4]],
	['vasodilatation', [4]],
	['vasodilators', [4]],
	['vein', [1]],
	['ventilated', [1]],
	['verapamil', [7]],
	['vessels', [4]],
	['via', [1, 3, 4, 6]],
	['virtual', [0]],
	['walls', [4]],
	['when', [2, 3]],
	['which', [0, 3, 4, 5, 6]],
	['whole', [0]],
	['widely', [0]],
	['within', [3]],
	['your', [2]]
];